/* tslint:disable */
/* eslint-disable */
/**
 * Mossem API
 * REST API for Mossem
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Configuration } from './configuration';
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface DanceDto
 */
export interface DanceDto {
    /**
     * 
     * @type {string}
     * @memberof DanceDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof DanceDto
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof DanceDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof DanceDto
     */
    description: string;
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary About this REST API
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        about: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Add new dance
         * @param {DanceDto} danceDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addDance: async (danceDto: DanceDto, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'danceDto' is not null or undefined
            assertParamExists('addDance', 'danceDto', danceDto)
            const localVarPath = `/dance`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(danceDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete dance with id {id}
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteDance: async (id: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteDance', 'id', id)
            const localVarPath = `/dance/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get information of dance with id {id}
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDance: async (id: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getDance', 'id', id)
            const localVarPath = `/dance/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get information of all dance
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDances: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/dance`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary update dance
         * @param {string} id 
         * @param {DanceDto} danceDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateDance: async (id: string, danceDto: DanceDto, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateDance', 'id', id)
            // verify required parameter 'danceDto' is not null or undefined
            assertParamExists('updateDance', 'danceDto', danceDto)
            const localVarPath = `/dance`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(danceDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary About this REST API
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async about(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.about(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Add new dance
         * @param {DanceDto} danceDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addDance(danceDto: DanceDto, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DanceDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addDance(danceDto, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Delete dance with id {id}
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteDance(id: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DanceDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteDance(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get information of dance with id {id}
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDance(id: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DanceDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDance(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get information of all dance
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDances(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<DanceDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDances(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary update dance
         * @param {string} id 
         * @param {DanceDto} danceDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateDance(id: string, danceDto: DanceDto, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateDance(id, danceDto, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary About this REST API
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        about(options?: any): AxiosPromise<void> {
            return localVarFp.about(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Add new dance
         * @param {DanceDto} danceDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addDance(danceDto: DanceDto, options?: any): AxiosPromise<DanceDto> {
            return localVarFp.addDance(danceDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete dance with id {id}
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteDance(id: string, options?: any): AxiosPromise<DanceDto> {
            return localVarFp.deleteDance(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get information of dance with id {id}
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDance(id: string, options?: any): AxiosPromise<DanceDto> {
            return localVarFp.getDance(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get information of all dance
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDances(options?: any): AxiosPromise<Array<DanceDto>> {
            return localVarFp.getDances(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary update dance
         * @param {string} id 
         * @param {DanceDto} danceDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateDance(id: string, danceDto: DanceDto, options?: any): AxiosPromise<void> {
            return localVarFp.updateDance(id, danceDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary About this REST API
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public about(options?: any) {
        return DefaultApiFp(this.configuration).about(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Add new dance
     * @param {DanceDto} danceDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public addDance(danceDto: DanceDto, options?: any) {
        return DefaultApiFp(this.configuration).addDance(danceDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete dance with id {id}
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public deleteDance(id: string, options?: any) {
        return DefaultApiFp(this.configuration).deleteDance(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get information of dance with id {id}
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getDance(id: string, options?: any) {
        return DefaultApiFp(this.configuration).getDance(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get information of all dance
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getDances(options?: any) {
        return DefaultApiFp(this.configuration).getDances(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary update dance
     * @param {string} id 
     * @param {DanceDto} danceDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public updateDance(id: string, danceDto: DanceDto, options?: any) {
        return DefaultApiFp(this.configuration).updateDance(id, danceDto, options).then((request) => request(this.axios, this.basePath));
    }
}


